events {}

http {
  upstream gateway_cluster {
    server api-gateway:5000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://gateway_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}